In [1]:
import pandas as pd

In [2]:
w = pd.read_csv("data/weather.csv")

C:\Users\asus\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (13,14,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
w.head()

,DATE,REPORT_TYPE,DailyAverageDewPointTemperature,DailyAverageDryBulbTemperature,DailyAverageWetBulbTemperature,DailyAverageWindSpeed,DailyMaximumDryBulbTemperature,DailyMinimumDryBulbTemperature,DailyPeakWindSpeed,DailyPrecipitation,...,MonthlyGreatestSnowDepthDate,MonthlyGreatestSnowfall,MonthlyGreatestSnowfallDate,MonthlyMaximumTemperature,MonthlyMeanTemperature,MonthlyMinimumTemperature,MonthlyTotalLiquidPrecipitation,MonthlyTotalSnowfall,Sunrise,Sunset
0,1/1/13 0:51,FM-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/1/13 1:51,FM-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/1/13 2:51,FM-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/1/13 3:51,FM-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/1/13 4:51,FM-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
w.columns.values

array(['DATE', 'REPORT_TYPE', 'DailyAverageDewPointTemperature',
       'DailyAverageDryBulbTemperature', 'DailyAverageWetBulbTemperature',
       'DailyAverageWindSpeed', 'DailyMaximumDryBulbTemperature',
       'DailyMinimumDryBulbTemperature', 'DailyPeakWindSpeed',
       'DailyPrecipitation', 'DailySnowDepth', 'DailySnowfall',
       'DailySustainedWindSpeed', 'HourlyDewPointTemperature',
       'HourlyDryBulbTemperature', 'HourlyPrecipitation',
       'HourlyWetBulbTemperature', 'HourlyWindGustSpeed',
       'HourlyWindSpeed', 'MonthlyDaysWithGT001Precip',
       'MonthlyDaysWithGT010Precip', 'MonthlyDaysWithGT32Temp',
       'MonthlyDaysWithGT90Temp', 'MonthlyDaysWithLT0Temp',
       'MonthlyDaysWithLT32Temp', 'MonthlyGreatestPrecip',
       'MonthlyGreatestPrecipDate', 'MonthlyGreatestSnowDepth',
       'MonthlyGreatestSnowDepthDate', 'MonthlyGreatestSnowfall',
       'MonthlyGreatestSnowfallDate', 'MonthlyMaximumTemperature',
       'MonthlyMeanTemperature', 'MonthlyMinimumTemperature',
       'MonthlyTotalLiquidPrecipitation', 'MonthlyTotalSnowfall',
       'Sunrise', 'Sunset'], dtype=object)

In [9]:
daily = w.filter(items=["DATE", "DailyAverageDryBulbTemperature", "Daily Percipitation", "DailySnowDepth", "DailySustainedWindSpeed"]).dropna()

In [11]:
daily.to_csv("data/nyc_daily_weather.csv", index=False)